name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ai-service:
    name: AI Service Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/ai

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Run format checks (isort and black)
        run: |
          poetry run isort --check-only app tests
          poetry run black --check app tests

      - name: Run linting (flake8)
        run: poetry run flake8 app tests

      - name: Run tests
        run: poetry run pytest

  web-service:
    name: Web Service Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/web

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: services/web/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run type checking
        run: npm run typecheck

      - name: Build check
        run: npm run build
        env:
          SKIP_ENV_VALIDATION: "1"
